server:
  port: 8765

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors: #CORS 설정
        corsConfigurations:
          '[**]':
            allowedOrigins: "*"

            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 1800

      routes:
        - id: routine-service
          url: lb://ROUTINE-SERVICE
          predicates:
            - Path=/routine/**
          filters:
            - RewritePath=/users/(?<segment>.*), /users/${segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG