server:
  port: 9000

eureka:
#  instance:
#    prefer-ip-address: true
#    ip-address: localhost
#    instance-id: ${eureka.instance.ip-address}:${server.port}
#    instance-id: ${eureka.instance.ip-address}:${random.value}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://routine-eureka:8765/eureka

spring:
  application:
    name: routine-gateway

  cloud:
    gateway:
      routes:
        - id: routine-test
          uri: http://routine-service:8080
          predicates:
            - Path=/hello

        - id: routine-service
          uri: http://routine-service:8080
          predicates:
            - Path=/routines/**
              #filters:
              #- RewritePath=/routines/(?<segment>/*), /${segment}

        #게이트웨이가 유레카에 등록된 서비스를 자동으로 라우팅하기 위함
#      discovery:
#        locator:
#          enabled: false
#          lower-case-service-id: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web.reactive: DEBUG
